### ISSUE TITLE
Pico CSS acting weird on nav

### ISSUE THREAD

**Issue by johnluther** [limeleaf-collective/limeleaf.io#9]
For some reason, Pico does a calculation for `margin-right` on the last nav `ul` that sets it to `-8.4px`. This offsets the nav box slightly, making it misaligned with the logo. On Safari iOS, this causes the word 'Contact' to get cut off and a horizontal slider to appear:

![IMG_0499](https://github.com/limeleaf-collective/limeleaf.io/assets/114623/13f0ff33-2a63-429c-b9e3-f4356dac4485)

This is the rule in `pico.min.css`: 

```
nav ol:last-of-type, nav ul:last-of-type {
    margin-right: calc(var(--pico-nav-element-spacing-horizontal) * -1);
}
```

Here it is on desktop with flex boxes visible to better illustrate:

<img width="371" alt="Screenshot 2024-04-20 at 1 23 43 PM" src="https://github.com/limeleaf-collective/limeleaf.io/assets/114623/654f0c6a-f351-4bbf-8211-0941cd2f16bd">

And the computed CSS box:

<img width="355" alt="Screenshot 2024-04-20 at 1 02 23 PM" src="https://github.com/limeleaf-collective/limeleaf.io/assets/114623/4060bafb-ad00-46a3-b5ee-7c692c30cdc1">

Adding this to `style.css` makes the behavior go away:

```
nav ul {
  margin: 0px !important;
}
```

I don't understand CSS or Pico well enough to understand why it's doing this, but it makes it annoying to scroll the pages on mobile.

**Comment by blainsmith** [comment]
It's odd the rows are not scaling to fit mobile either. Might be as simple as not using the Pico nav structure and just let the logo and menu be on separate rows in the grid and center them. :shrug:
